### ISSUE TITLE
FLIR UI stuck on

### ISSUE THREAD

**Issue by ampersand38** [Project-Hatchet/public_h-60#101]
# Prerequisites

Please answer the following questions for yourself before submitting an issue. 

- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this [issue](https://github.com/Project-Hatchet/public_h-60/issues?q=is%3Aissue+label%3Abug+) has not already been filed
- [x] I checked the [FAQ](https://discord.gg/4AYEfFD) and known bugs on the discord
  
# Bug Report

## **Description:**

Bugged version of FLIR camera ui stuck on for DAP and RHS MELB

### **Screenshots**

https://cdn.discordapp.com/attachments/649639821505069065/816057315047374848/ArmA_3_Screenshot_2021.03.01_-_23.19.19.83.png

**Comment by YannikH** [comment]
fixed for the MELB in #106

**Comment by BroBeansCPG** [comment]
https://clips.twitch.tv/MoistColorfulRavenTooSpicy-BtdlhPjVuaCJcYf9

Still present when remote controlling AI pilot, also Help UI is stuck on
